use crate::{Analysis, GapItem};

pub struct ScaffoldOutput {
    pub rust: String,
    pub cargo_deps: Vec<String>,
}

fn emit_gap(out: &mut String, deps: &mut Vec<String>, g: &GapItem) {
    if let Some(plugin) = &g.plugin {
        deps.push(format!("{plugin} = \"2\""));
        out.push_str(&format!(
            "    // {} ({}) — official plugin\n    .plugin({}::init())\n",
            g.name,
            g.id,
            plugin.replace('-', "_")
        ));
    } else if let Some(krate) = &g.crate_name {
        deps.push(format!("{krate} = \"*\""));
        out.push_str(&format!(
            "    // {} ({}) — proven crate: {}\n    // TODO wire {}; see crate docs\n",
            g.name, g.id, krate, krate
        ));
    } else {
        out.push_str(&format!(
            "    // {} ({}) — no proven recipe; implement manually\n    // stub:\n    // fn {}() {{ todo!(\"implement {}\") }}\n",
            g.name,
            g.id,
            g.id.replace('.', "_"),
            g.id
        ));
    }
}

pub fn scaffold(a: &Analysis) -> ScaffoldOutput {
    let mut rust = String::from("// Generated by wrap-swap scaffold. Review before use.\n");
    rust.push_str(
        "pub fn register(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {\n    builder\n",
    );
    let mut deps = Vec::new();
    for g in &a.gaps {
        emit_gap(&mut rust, &mut deps, g);
    }
    rust.push_str("}\n");
    deps.sort();
    deps.dedup();
    ScaffoldOutput {
        rust,
        cargo_deps: deps,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{analyze, Matrix, Profile, Source};

    #[test]
    fn proven_rows_emit_real_wiring_others_stub() {
        let m = Matrix::embedded();
        let p = Profile {
            source: Source::Electron,
            capabilities: vec![
                "electron.global_shortcut".into(),
                "uwp.background_tasks".into(),
            ],
        };
        let out = scaffold(&analyze(&m, &p));
        assert!(out
            .cargo_deps
            .iter()
            .any(|d| d.contains("tauri-plugin-global-shortcut")));
        assert!(out.rust.contains(".plugin("));
        assert!(out.rust.contains("todo!("));
    }
}
