use crate::{Analysis, GapItem};

pub struct ScaffoldOutput {
    pub rust: String,
    pub cargo_deps: Vec<String>,
}

fn emit_gap(out: &mut String, deps: &mut Vec<String>, g: &GapItem) {
    if let Some(plugin) = &g.plugin {
        deps.push(format!("{plugin} = \"2\""));
        // Only a verified drop-in gets emitted as code. Plugins that need developer
        // configuration (a KDF, a callback, ...) have no `init()` and must NOT be wired
        // blindly — that produced code which did not compile against the real crate.
        let init = g
            .init_expr
            .clone()
            .unwrap_or_else(|| format!("{}::init()", plugin.replace('-', "_")));
        if g.recipe == Some(crate::Recipe::Proven) {
            out.push_str(&format!(
                "    // {} ({}) — official plugin\n    .plugin({})\n",
                g.name, g.id, init
            ));
        } else {
            out.push_str(&format!(
                "    // {} ({}) — plugin `{}` needs configuration; not a drop-in.\n    \
// Add the dependency, then wire it yourself, e.g.:\n    //   .plugin({})\n",
                g.name, g.id, plugin, init
            ));
        }
    } else if let Some(krate) = &g.crate_name {
        let ver = g.crate_version.as_deref().unwrap_or("*");
        deps.push(format!("{krate} = \"{ver}\""));
        out.push_str(&format!(
            "    // {} ({}) — proven crate: {}\n    // TODO wire {}; see crate docs\n",
            g.name, g.id, krate, krate
        ));
    } else {
        out.push_str(&format!(
            "    // {} ({}) — no proven recipe; implement manually\n    // stub:\n    // fn {}() {{ todo!(\"implement {}\") }}\n",
            g.name,
            g.id,
            g.id.replace('.', "_"),
            g.id
        ));
    }
}

pub fn scaffold(a: &Analysis) -> ScaffoldOutput {
    let mut rust = String::from("// Generated by assay scaffold. Review before use.\n");
    rust.push_str(
        "pub fn register(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {\n    builder\n",
    );
    // The generated `register()` signature references `tauri::Builder`, so tauri itself is
    // always a required dependency — not just the per-gap plugins.
    let mut deps = vec!["tauri = \"2\"".to_string()];
    for g in &a.gaps {
        emit_gap(&mut rust, &mut deps, g);
    }
    rust.push_str("}\n");
    deps.sort();
    deps.dedup();
    ScaffoldOutput {
        rust,
        cargo_deps: deps,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{analyze, Matrix, Profile, Source};

    #[test]
    fn proven_rows_emit_real_wiring_others_stub() {
        let m = Matrix::embedded();
        let p = Profile {
            source: Source::Electron,
            capabilities: vec![
                "electron.global_shortcut".into(),
                "uwp.background_tasks".into(),
            ],
        };
        let out = scaffold(&analyze(&m, &p));
        assert!(out
            .cargo_deps
            .iter()
            .any(|d| d.contains("tauri-plugin-global-shortcut")));
        assert!(out.rust.contains(".plugin("));
        assert!(out.rust.contains("todo!("));
    }

    #[test]
    fn generated_bridge_is_valid_rust_syntax() {
        let m = Matrix::embedded();
        // Mix of every path kind: plugin, native, custom_rust-with-recipe, and a stub.
        let p = Profile {
            source: Source::Electron,
            capabilities: vec![
                "electron.global_shortcut".into(), // plugin
                "electron.ipc".into(),             // native (proven, no plugin/crate)
                "uwp.toast".into(),                // proven crate
                "uwp.background_tasks".into(),     // custom_rust, no recipe -> stub
            ],
        };
        let out = scaffold(&analyze(&m, &p));
        syn::parse_file(&out.rust)
            .unwrap_or_else(|e| panic!("generated bridge.rs is not valid Rust: {e}\n{}", out.rust));
    }

    /// Golden snapshot: lock the full generated bridge against silent drift.
    #[test]
    fn golden_bridge_rs() {
        let m = Matrix::embedded();
        let p = Profile {
            source: Source::Electron,
            capabilities: vec![
                "electron.global_shortcut".into(),
                "electron.ipc".into(),
                "uwp.toast".into(),
                "uwp.background_tasks".into(),
            ],
        };
        let out = scaffold(&analyze(&m, &p));
        insta::assert_snapshot!(out.rust);
        insta::assert_snapshot!("bridge_deps", out.cargo_deps.join("\n"));
    }
}
