//! Sidecar native-module migration kit (BACKLOG §5.3 / spec
//! `docs/superpowers/specs/2026-07-23-sidecar-migration-kit-design.md`).
//!
//! Given the native modules detected in an Electron project
//! ([`crate::parse::detect_native_modules`]), generate a runnable **sidecar** skeleton
//! that speaks a line-delimited JSON protocol over stdio, a Tauri-side client, and a
//! per-module migration checklist. No module logic is ported — every handler is a
//! `todo!()` stub carrying its detection reason (honesty invariant).

use crate::parse::NativeModule;

/// The generated artifacts for one project's sidecar migration.
pub struct SidecarKit {
    pub cargo_toml: String,
    pub main_rs: String,
    pub client_rs: String,
    pub migration_md: String,
    /// `tauri.conf.json` fragment registering the sidecar as an external binary
    /// and granting the shell-execute permission it needs.
    pub tauri_conf_snippet: String,
}

/// The `tauri.conf.json` fragment to merge into the host app's config.
///
/// `externalBin` paths are resolved by Tauri with a target-triple suffix, so the
/// bundled binary must be named `sidecar-<triple>(.exe)`.
fn gen_tauri_conf_snippet() -> String {
    "{\n  \"bundle\": {\n    \"externalBin\": [\n      \"binaries/sidecar\"\n    ]\n  },\n  \"plugins\": {\n    \"shell\": {\n      \"sidecar\": true,\n      \"scope\": [\n        {\n          \"name\": \"binaries/sidecar\",\n          \"sidecar\": true,\n          \"args\": false\n        }\n      ]\n    }\n  }\n}\n"
        .to_string()
}

fn gen_cargo_toml() -> String {
    "[package]\n\
name = \"sidecar\"\n\
version = \"0.1.0\"\n\
edition = \"2021\"\n\
publish = false\n\
\n\
[dependencies]\n\
serde_json = \"1\"\n"
        .to_string()
}

fn gen_main_rs(modules: &[NativeModule]) -> String {
    let mut arms = String::new();
    for m in modules {
        arms.push_str(&format!(
            "        {:?} => {{\n            // detected: {}\n            let _ = &id;\n            todo!(\"port {} to Rust\")\n        }}\n",
            m.name, m.detection_reason, m.name
        ));
    }
    format!(
        "// Generated by assay sidecar. Review before use. No module logic is ported.\n\
// Protocol: one JSON request per line on stdin -> one JSON response per line on stdout.\n\
// request:  {{\"id\":N,\"module\":\"...\",\"method\":\"...\",\"args\":[...]}}\n\
// response: {{\"id\":N,\"ok\":true,\"result\":...}} | {{\"id\":N,\"ok\":false,\"error\":\"...\"}}\n\
use std::io::{{BufRead, Write}};\n\
\n\
fn main() {{\n\
    let stdin = std::io::stdin();\n\
    let mut stdout = std::io::stdout();\n\
    for line in stdin.lock().lines() {{\n\
        let line = match line {{ Ok(l) => l, Err(_) => break }};\n\
        if line.trim().is_empty() {{ continue; }}\n\
        let resp = handle(&line);\n\
        let _ = writeln!(stdout, \"{{}}\", resp);\n\
        let _ = stdout.flush();\n\
    }}\n\
}}\n\
\n\
fn handle(request: &str) -> String {{\n\
    let v: serde_json::Value = match serde_json::from_str(request) {{\n\
        Ok(v) => v,\n\
        Err(e) => return format!(\"{{{{\\\"ok\\\":false,\\\"error\\\":\\\"bad json: {{}}\\\"}}}}\", e),\n\
    }};\n\
    let id = v.get(\"id\").cloned().unwrap_or(serde_json::Value::Null);\n\
    let module = v.get(\"module\").and_then(|m| m.as_str()).unwrap_or(\"\");\n\
    match module {{\n\
{arms}\
        other => format!(\"{{{{\\\"id\\\":{{}},\\\"ok\\\":false,\\\"error\\\":\\\"unknown module {{}}\\\"}}}}\", id, other),\n\
    }}\n\
}}\n"
    )
}

fn gen_client_rs() -> String {
    "// Generated by assay. Minimal stdio client for the sidecar process.\n\
use std::io::{BufRead, BufReader, Write};\n\
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};\n\
\n\
pub struct SidecarClient {\n\
    child: Child,\n\
    stdin: ChildStdin,\n\
    reader: BufReader<ChildStdout>,\n\
    next_id: u64,\n\
}\n\
\n\
impl SidecarClient {\n\
    pub fn spawn(exe: &str) -> std::io::Result<SidecarClient> {\n\
        let mut child = Command::new(exe)\n\
            .stdin(Stdio::piped())\n\
            .stdout(Stdio::piped())\n\
            .spawn()?;\n\
        let stdin = child.stdin.take().expect(\"stdin\");\n\
        let stdout = child.stdout.take().expect(\"stdout\");\n\
        Ok(SidecarClient { child, stdin, reader: BufReader::new(stdout), next_id: 1 })\n\
    }\n\
\n\
    pub fn call(&mut self, module: &str, method: &str, args: &str) -> std::io::Result<String> {\n\
        let id = self.next_id;\n\
        self.next_id += 1;\n\
        let req = format!(\n\
            \"{{\\\"id\\\":{},\\\"module\\\":\\\"{}\\\",\\\"method\\\":\\\"{}\\\",\\\"args\\\":{}}}\",\n\
            id, module, method, args\n\
        );\n\
        writeln!(self.stdin, \"{}\", req)?;\n\
        self.stdin.flush()?;\n\
        let mut line = String::new();\n\
        self.reader.read_line(&mut line)?;\n\
        Ok(line)\n\
    }\n\
\n\
    pub fn shutdown(mut self) {\n\
        let _ = self.child.kill();\n\
    }\n\
}\n"
        .to_string()
}

fn gen_migration_md(modules: &[NativeModule]) -> String {
    let mut out = String::from(
        "# Native-Module Migration Checklist\n\n\
Generated by assay. Each module below was detected in the Electron project and needs a\n\
decision: **reimplement in Rust** (a Tauri command) or **keep as a sidecar** (fill its handler\n\
in `sidecar/src/main.rs`). No logic has been ported.\n\n\
| Module | Why flagged | Prebuilds | Decision (reimplement / sidecar) |\n\
|---|---|---|---|\n",
    );
    if modules.is_empty() {
        out.push_str("| _(none detected)_ | | | |\n");
    }
    for m in modules {
        out.push_str(&format!(
            "| `{}` | {} | {} | _TODO_ |\n",
            m.name,
            m.detection_reason,
            if m.has_prebuilds { "yes" } else { "no" }
        ));
    }
    out
}

/// Generate the full sidecar migration kit for the detected modules.
pub fn generate_sidecar(modules: &[NativeModule]) -> SidecarKit {
    SidecarKit {
        cargo_toml: gen_cargo_toml(),
        main_rs: gen_main_rs(modules),
        client_rs: gen_client_rs(),
        migration_md: gen_migration_md(modules),
        tauri_conf_snippet: gen_tauri_conf_snippet(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Vec<NativeModule> {
        vec![
            NativeModule {
                name: "serialport".into(),
                detection_reason: "commonly-native package `serialport`".into(),
                has_prebuilds: true,
            },
            NativeModule {
                name: "keytar".into(),
                detection_reason: "commonly-native package `keytar`".into(),
                has_prebuilds: false,
            },
        ]
    }

    #[test]
    fn generated_main_and_client_are_valid_rust() {
        let kit = generate_sidecar(&sample());
        syn::parse_file(&kit.main_rs)
            .unwrap_or_else(|e| panic!("main.rs invalid: {e}\n{}", kit.main_rs));
        syn::parse_file(&kit.client_rs)
            .unwrap_or_else(|e| panic!("client.rs invalid: {e}\n{}", kit.client_rs));
    }

    #[test]
    fn main_rs_has_a_stub_arm_per_module() {
        let kit = generate_sidecar(&sample());
        assert!(kit.main_rs.contains("\"serialport\" =>"));
        assert!(kit.main_rs.contains("\"keytar\" =>"));
        assert_eq!(kit.main_rs.matches("todo!(").count(), 2);
    }

    #[test]
    fn migration_md_lists_modules() {
        let kit = generate_sidecar(&sample());
        assert!(kit.migration_md.contains("| `serialport` |"));
        assert!(kit.migration_md.contains("yes")); // serialport prebuilds
    }

    #[test]
    fn empty_project_still_produces_valid_artifacts() {
        let kit = generate_sidecar(&[]);
        syn::parse_file(&kit.main_rs).expect("main.rs valid for empty");
        assert!(kit.migration_md.contains("none detected"));
    }

    #[test]
    fn tauri_conf_snippet_is_valid_json_registering_the_sidecar() {
        let kit = generate_sidecar(&sample());
        let v: serde_json::Value =
            serde_json::from_str(&kit.tauri_conf_snippet).expect("snippet is valid JSON");
        assert_eq!(
            v["bundle"]["externalBin"][0].as_str(),
            Some("binaries/sidecar")
        );
        assert_eq!(v["plugins"]["shell"]["sidecar"].as_bool(), Some(true));
    }

    // Golden snapshots: lock the full generated output against silent drift.
    #[test]
    fn golden_sidecar_main_rs() {
        insta::assert_snapshot!(generate_sidecar(&sample()).main_rs);
    }

    #[test]
    fn golden_sidecar_client_rs() {
        insta::assert_snapshot!(generate_sidecar(&sample()).client_rs);
    }

    #[test]
    fn golden_sidecar_migration_md() {
        insta::assert_snapshot!(generate_sidecar(&sample()).migration_md);
    }
}
